/*
  # Add Comprehensive Stripe Event Schema

  ## 1. New Tables
    - `stripe_events` - Master event log for all Stripe webhooks (idempotent)
    - `stripe_connect_accounts` - Full Connect account tracking (separate from creators)
    - `stripe_customers` - Customer mapping (complements fan_profiles)
    - `stripe_subscriptions` - Enhanced subscription tracking with full Stripe data
    - `stripe_payments` - Payment intent and charge tracking
    - `stripe_payouts` - Creator payout tracking
    - `stripe_disputes` - Chargeback and dispute management

  ## 2. Indexes
    - Foreign key indexes for performance
    - Event type and timestamp indexes for querying
    - Stripe ID indexes for webhook lookups

  ## 3. Security
    - RLS enabled on all tables
    - Admins can view all data for support
    - Users can view their own data only
    - Creators can view their payout/payment data

  ## 4. Purpose
    - Full audit trail of all Stripe events
    - Idempotent webhook processing (prevent duplicates)
    - Event replay capability
    - Payment history for disputes & refunds
    - Payout tracking for creator earnings
    - Comprehensive financial reporting

  ## Notes
    - Existing subscriptions table is kept for backward compatibility
    - New stripe_subscriptions table provides enhanced tracking
    - All tables use JSONB for full Stripe object storage
*/

-- ============================================
-- 1. Master Stripe Event Log Table
-- ============================================
-- Stores every webhook from Stripe for idempotency and replay

CREATE TABLE IF NOT EXISTS public.stripe_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_event_id text UNIQUE NOT NULL,
  event_type text NOT NULL,
  data jsonb NOT NULL,
  processed boolean DEFAULT false,
  attempts int DEFAULT 0,
  error_message text,
  created_at timestamptz DEFAULT now(),
  processed_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_stripe_events_event_type 
  ON public.stripe_events(event_type);
CREATE INDEX IF NOT EXISTS idx_stripe_events_created_at 
  ON public.stripe_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stripe_events_processed 
  ON public.stripe_events(processed) WHERE processed = false;
CREATE INDEX IF NOT EXISTS idx_stripe_events_stripe_id 
  ON public.stripe_events(stripe_event_id);

COMMENT ON TABLE public.stripe_events IS 'Master log of all Stripe webhook events for idempotency and replay';
COMMENT ON COLUMN public.stripe_events.stripe_event_id IS 'Stripe event ID (evt_...) for idempotency';
COMMENT ON COLUMN public.stripe_events.processed IS 'Whether the event has been processed by our application';
COMMENT ON COLUMN public.stripe_events.attempts IS 'Number of processing attempts (for retry logic)';

ALTER TABLE public.stripe_events ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 2. Stripe Customers Table
-- ============================================
-- Maps auth.users to Stripe customer IDs (complements fan_profiles)

CREATE TABLE IF NOT EXISTS public.stripe_customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  stripe_customer_id text UNIQUE NOT NULL,
  email text,
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stripe_customers_user_id 
  ON public.stripe_customers(user_id);
CREATE INDEX IF NOT EXISTS idx_stripe_customers_customer_id 
  ON public.stripe_customers(stripe_customer_id);

COMMENT ON TABLE public.stripe_customers IS 'Maps users to Stripe customer IDs';

ALTER TABLE public.stripe_customers ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 3. Stripe Connect Accounts Table
-- ============================================
-- Detailed tracking of creator Connect accounts

CREATE TABLE IF NOT EXISTS public.stripe_connect_accounts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  stripe_account_id text UNIQUE NOT NULL,
  details_submitted boolean DEFAULT false,
  payouts_enabled boolean DEFAULT false,
  charges_enabled boolean DEFAULT false,
  requirements jsonb,
  capabilities jsonb,
  country text,
  default_currency text DEFAULT 'usd',
  metadata jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_connect_accounts_user_id 
  ON public.stripe_connect_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_connect_accounts_stripe_id 
  ON public.stripe_connect_accounts(stripe_account_id);

COMMENT ON TABLE public.stripe_connect_accounts IS 'Detailed tracking of Stripe Connect accounts for creators';
COMMENT ON COLUMN public.stripe_connect_accounts.requirements IS 'Stripe requirements object (fields needed for onboarding)';
COMMENT ON COLUMN public.stripe_connect_accounts.capabilities IS 'Account capabilities (card_payments, transfers, etc.)';

ALTER TABLE public.stripe_connect_accounts ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 4. Enhanced Stripe Subscriptions Table
-- ============================================
-- Full subscription tracking with Stripe data

CREATE TABLE IF NOT EXISTS public.stripe_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_subscription_id text UNIQUE NOT NULL,
  stripe_customer_id text NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  creator_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at timestamptz,
  canceled_at timestamptz,
  ended_at timestamptz,
  trial_start timestamptz,
  trial_end timestamptz,
  amount integer,
  currency text DEFAULT 'usd',
  data jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_stripe_subscriptions_sub_id 
  ON public.stripe_subscriptions(stripe_subscription_id);
CREATE INDEX IF NOT EXISTS idx_stripe_subscriptions_user_id 
  ON public.stripe_subscriptions(user_id);
CREATE INDEX IF NOT EXISTS idx_stripe_subscriptions_creator_id 
  ON public.stripe_subscriptions(creator_id);
CREATE INDEX IF NOT EXISTS idx_stripe_subscriptions_status 
  ON public.stripe_subscriptions(status);
CREATE INDEX IF NOT EXISTS idx_stripe_subscriptions_customer_id 
  ON public.stripe_subscriptions(stripe_customer_id);

COMMENT ON TABLE public.stripe_subscriptions IS 'Enhanced subscription tracking with full Stripe data';
COMMENT ON COLUMN public.stripe_subscriptions.data IS 'Full Stripe subscription object';

ALTER TABLE public.stripe_subscriptions ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 5. Stripe Payments Table
-- ============================================
-- Track all payment intents and charges

CREATE TABLE IF NOT EXISTS public.stripe_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_payment_intent_id text UNIQUE NOT NULL,
  stripe_charge_id text,
  stripe_customer_id text,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  creator_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  amount integer NOT NULL,
  amount_received integer,
  application_fee_amount integer,
  currency text DEFAULT 'usd',
  status text NOT NULL,
  description text,
  receipt_email text,
  metadata jsonb,
  data jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payments_intent_id 
  ON public.stripe_payments(stripe_payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_payments_charge_id 
  ON public.stripe_payments(stripe_charge_id);
CREATE INDEX IF NOT EXISTS idx_payments_user 
  ON public.stripe_payments(user_id);
CREATE INDEX IF NOT EXISTS idx_payments_creator 
  ON public.stripe_payments(creator_id);
CREATE INDEX IF NOT EXISTS idx_payments_customer 
  ON public.stripe_payments(stripe_customer_id);
CREATE INDEX IF NOT EXISTS idx_payments_status 
  ON public.stripe_payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_created 
  ON public.stripe_payments(created_at DESC);

COMMENT ON TABLE public.stripe_payments IS 'All payment intents and charges for audit trail';
COMMENT ON COLUMN public.stripe_payments.application_fee_amount IS 'Platform fee taken (10% for peak.boo)';
COMMENT ON COLUMN public.stripe_payments.data IS 'Full Stripe PaymentIntent object';

ALTER TABLE public.stripe_payments ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 6. Stripe Payouts Table
-- ============================================
-- Track payouts to creator bank accounts

CREATE TABLE IF NOT EXISTS public.stripe_payouts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_payout_id text UNIQUE NOT NULL,
  stripe_account_id text NOT NULL,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  amount integer NOT NULL,
  currency text DEFAULT 'usd',
  status text NOT NULL,
  arrival_date timestamptz,
  automatic boolean DEFAULT true,
  description text,
  failure_code text,
  failure_message text,
  method text,
  type text,
  data jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_payouts_payout_id 
  ON public.stripe_payouts(stripe_payout_id);
CREATE INDEX IF NOT EXISTS idx_payouts_stripe_account 
  ON public.stripe_payouts(stripe_account_id);
CREATE INDEX IF NOT EXISTS idx_payouts_user 
  ON public.stripe_payouts(user_id);
CREATE INDEX IF NOT EXISTS idx_payouts_status 
  ON public.stripe_payouts(status);
CREATE INDEX IF NOT EXISTS idx_payouts_created 
  ON public.stripe_payouts(created_at DESC);

COMMENT ON TABLE public.stripe_payouts IS 'Tracks all payouts to creator bank accounts';
COMMENT ON COLUMN public.stripe_payouts.data IS 'Full Stripe Payout object';

ALTER TABLE public.stripe_payouts ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 7. Stripe Disputes Table
-- ============================================
-- Track chargebacks and disputes

CREATE TABLE IF NOT EXISTS public.stripe_disputes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stripe_dispute_id text UNIQUE NOT NULL,
  stripe_charge_id text,
  stripe_payment_intent_id text,
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  creator_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  amount integer NOT NULL,
  currency text DEFAULT 'usd',
  reason text,
  status text NOT NULL,
  evidence jsonb,
  evidence_details jsonb,
  is_charge_refundable boolean,
  metadata jsonb,
  data jsonb,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_disputes_dispute_id 
  ON public.stripe_disputes(stripe_dispute_id);
CREATE INDEX IF NOT EXISTS idx_disputes_charge_id 
  ON public.stripe_disputes(stripe_charge_id);
CREATE INDEX IF NOT EXISTS idx_disputes_user 
  ON public.stripe_disputes(user_id);
CREATE INDEX IF NOT EXISTS idx_disputes_creator 
  ON public.stripe_disputes(creator_id);
CREATE INDEX IF NOT EXISTS idx_disputes_status 
  ON public.stripe_disputes(status);
CREATE INDEX IF NOT EXISTS idx_disputes_created 
  ON public.stripe_disputes(created_at DESC);

COMMENT ON TABLE public.stripe_disputes IS 'Tracks chargebacks and disputes from customers';
COMMENT ON COLUMN public.stripe_disputes.evidence IS 'Evidence submitted to fight the dispute';
COMMENT ON COLUMN public.stripe_disputes.data IS 'Full Stripe Dispute object';

ALTER TABLE public.stripe_disputes ENABLE ROW LEVEL SECURITY;

-- ============================================
-- RLS POLICIES - Stripe Events
-- ============================================

CREATE POLICY "Admins can view all stripe events"
  ON public.stripe_events FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.creators 
      WHERE user_id = (select auth.uid()) AND is_admin = true
    )
  );

CREATE POLICY "System can insert stripe events"
  ON public.stripe_events FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update stripe events"
  ON public.stripe_events FOR UPDATE
  TO authenticated
  USING (true);

-- ============================================
-- RLS POLICIES - Stripe Customers
-- ============================================

CREATE POLICY "Users can view own customer data"
  ON public.stripe_customers FOR SELECT
  TO authenticated
  USING (
    user_id = (select auth.uid()) OR
    EXISTS (
      SELECT 1 FROM public.creators 
      WHERE user_id = (select auth.uid()) AND is_admin = true
    )
  );

CREATE POLICY "System can insert customer data"
  ON public.stripe_customers FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update customer data"
  ON public.stripe_customers FOR UPDATE
  TO authenticated
  USING (true);

-- ============================================
-- RLS POLICIES - Stripe Connect Accounts
-- ============================================

CREATE POLICY "Users can view own connect account"
  ON public.stripe_connect_accounts FOR SELECT
  TO authenticated
  USING (
    user_id = (select auth.uid()) OR
    EXISTS (
      SELECT 1 FROM public.creators 
      WHERE user_id = (select auth.uid()) AND is_admin = true
    )
  );

CREATE POLICY "System can insert connect accounts"
  ON public.stripe_connect_accounts FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update connect accounts"
  ON public.stripe_connect_accounts FOR UPDATE
  TO authenticated
  USING (true);

-- ============================================
-- RLS POLICIES - Stripe Subscriptions
-- ============================================

CREATE POLICY "Users can view own subscriptions data"
  ON public.stripe_subscriptions FOR SELECT
  TO authenticated
  USING (
    user_id = (select auth.uid()) OR
    creator_id = (select auth.uid()) OR
    EXISTS (
      SELECT 1 FROM public.creators 
      WHERE user_id = (select auth.uid()) AND is_admin = true
    )
  );

CREATE POLICY "System can insert subscription data"
  ON public.stripe_subscriptions FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update subscription data"
  ON public.stripe_subscriptions FOR UPDATE
  TO authenticated
  USING (true);

-- ============================================
-- RLS POLICIES - Stripe Payments
-- ============================================

CREATE POLICY "Users can view own payment data"
  ON public.stripe_payments FOR SELECT
  TO authenticated
  USING (
    user_id = (select auth.uid()) OR
    creator_id = (select auth.uid()) OR
    EXISTS (
      SELECT 1 FROM public.creators 
      WHERE user_id = (select auth.uid()) AND is_admin = true
    )
  );

CREATE POLICY "System can insert payment data"
  ON public.stripe_payments FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update payment data"
  ON public.stripe_payments FOR UPDATE
  TO authenticated
  USING (true);

-- ============================================
-- RLS POLICIES - Stripe Payouts
-- ============================================

CREATE POLICY "Creators can view own payout data"
  ON public.stripe_payouts FOR SELECT
  TO authenticated
  USING (
    user_id = (select auth.uid()) OR
    EXISTS (
      SELECT 1 FROM public.creators 
      WHERE user_id = (select auth.uid()) AND is_admin = true
    )
  );

CREATE POLICY "System can insert payout data"
  ON public.stripe_payouts FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update payout data"
  ON public.stripe_payouts FOR UPDATE
  TO authenticated
  USING (true);

-- ============================================
-- RLS POLICIES - Stripe Disputes
-- ============================================

CREATE POLICY "Users can view disputes involving them"
  ON public.stripe_disputes FOR SELECT
  TO authenticated
  USING (
    user_id = (select auth.uid()) OR
    creator_id = (select auth.uid()) OR
    EXISTS (
      SELECT 1 FROM public.creators 
      WHERE user_id = (select auth.uid()) AND is_admin = true
    )
  );

CREATE POLICY "System can insert dispute data"
  ON public.stripe_disputes FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "System can update dispute data"
  ON public.stripe_disputes FOR UPDATE
  TO authenticated
  USING (true);
